import {
  FiMessageCircle,
  FiBarChart2,
  FiSmartphone,
  FiTrendingUp,
} from "react-icons/fi";

export const PROJECTS = [
  {
    id: "umbrachat",
    icon: FiMessageCircle,
    techStack: [
      "React",
      "Next.js",
      "NestJS",
      "PostgreSQL",
      "Docker",
      "AWS",
      "Nginx",
      "TypeScript",
      "Tailwind CSS",
      "CSS3",
      "HTML5",
    ],
    githubUrl: "https://github.com/grecod28/umbrachat",
    liveUrl: "https://umbrachat.org",
    ImageSrc: "/images/projects/umbrachat.png",
    featured: true,
  },
  {
    id: "knowmeet",
    icon: FiSmartphone,
    techStack: [
      "React",
      "React Native",
      "TypeScript",
      "Node.js",
      "Tailwind CSS",
      "PostgreSQL",
      "Docker",
    ],
    githubUrl: undefined,
    liveUrl:
      "https://play.google.com/store/apps/details?id=com.grecod28.knowmeetapp",
    ImageSrc: "/images/projects/knowmeet.png",
    featured: true,
  },
  {
    id: "k2studio",
    icon: FiTrendingUp,
    techStack: [
      "Astro",
      "TypeScript",
      "Tailwind CSS",
      "AWS",
      "GitHub Actions",
      "HTML5",
      "CSS3",
    ],
    githubUrl: "https://github.com/grecod28/k2",
    liveUrl: "https://studiok2.es",
    ImageSrc: "/images/projects/k2.png",
    featured: true,
  },
  {
    id: "devfolio",
    icon: FiBarChart2,
    techStack: [
      "React",
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "HTML5",
      "CSS3",
    ],
    githubUrl: "https://github.com/grecod28/grecodev",
    ImageSrc: "/images/projects/devfolio.png",
    featured: false,
  },
];
